### ISSUE TITLE
Eclipse Tycho: Link to Git Repo doesn't get interpreted as Link

### ISSUE THREAD

**Issue by fap-** [vogellacompany/com.vogella.tutorials.eclipse#3]
Maybe this is a feature request for Asciidoctor?

![eclipse tycho for building eclipse plug-ins osgi bundles and rcp applications - tutorial - chromium_033](https://cloud.githubusercontent.com/assets/459631/20786618/5f8fbde8-b7a7-11e6-8993-a5f8acaff43f.png)

**Comment by vogella** [comment]
I suggest to change it to a http://git.eclipse.org/r link.

@fap- can you do the change?

Am 01.12.2016 9:20 vorm. schrieb "FAP" <notifications@github.com>:

**Comment by fap-** [comment]
Done. https://github.com/vogellacompany/com.vogella.tutorials.eclipse/commit/75aee1a0088143e261ddd328dc95f5d348101fb2

**Comment by vogella** [comment]
Thanks

Am 01.12.2016 9:34 vorm. schrieb "FAP" <notifications@github.com>:
