### ISSUE TITLE
Dead link in EclipsePlatformDevelopment

### ISSUE THREAD

**Issue by fap-** [vogellacompany/com.vogella.tutorials.eclipse#5]
I'm not sure where this is supposed to link to.

https://github.com/vogellacompany/com.vogella.tutorials.eclipse/blob/master/EclipsePlatformDevelopment/400_platformbuilds.adoc

![selection_035](https://cloud.githubusercontent.com/assets/459631/20954371/0ca11c1a-bc3b-11e6-902d-c58e094070ff.png)

**Comment by vogella** [comment]
I updated the description. Thanks @fap-
